### ISSUE TITLE
ansible how to have monitor many JVM on a same host

### ISSUE THREAD

**Issue by ybr** [ybr/ybr.github.io#4]
Create fragments with template module then assmble them with assemble module

In datadog agent configuration folder
```
/etc/dd-agent/conf.d/jmx/fragment.0.header.yaml
/etc/dd-agent/conf.d/jmx/fragment.roleApp1.yaml
/etc/dd-agent/conf.d/jmx/fragment.roleApp2.yaml
```

assemble to
```/etc/dd-agent/conf.d/jmx.yaml```

RoleApp1
```
- name: datadog
  template: src=datadog-jmx.j2.yaml dest=/etc/dd-agent/conf.d/jmx/fragment.roleApp1.yaml
  notify: datadog assemble jmx
```

datadog handlers
```
- name: datadog prepare assemble jmx
  template:
    src: datadog-jmx.j2.yaml
    dest: /etc/dd-agent/conf.d/jmx/fragment.0.header.yaml # Files are assembled in string sorting order
  listen: datadog assemble jmx

- name: datadog do assemble jmx
  assemble:
    src: /etc/dd-agent/conf.d/jmx
    dest: /etc/dd-agent/conf.d/jmx.yaml
    regexp: ".*\\.yaml"
    delimiter: '### START FRAGMENT ###'
    backup: yes
  listen: datadog assemble jmx
```
