### ISSUE TITLE
provide programmatically a dictionnary for docker_container.etc_hosts

### ISSUE THREAD

**Issue by ybr** [ybr/ybr.github.io#5]
```
- name : start
  docker_container:
    name: ckh
    image: registry.mycompany.com:5000/ica/clickhouse:{{ TAG }}
    state: started
    ports:
    - "8123:8123"
    - "9000:9000"
    - "9009:9009"
    volumes:
    - /opt/clickhouse-server/clickhouse.xml:/etc/clickhouse-server/conf.d/config.xml
    - /data/clickhouse:/var/lib/clickhouse
    # volumes_from:
    # - ckh_data
    etc_hosts: |
      {% set dict = {} -%}
      {%- for host in groups["clickhouse"] -%}
        {% set ignored = dict.update({ host : host }) %}
      {%- endfor %}
      {{ dict }}
```
